version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "5001:5000"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  db:
    image: mongo
    volumes:
      - ./db/mongo-data:/data/db
    ports:
      - "27017:27017"
